In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder
import numpy as np

https://archive.ics.uci.edu/ml/datasets/Census%2BIncome

Donor: Ronny Kohavi and Barry Becker,

       Data Mining and Visualization
       Silicon Graphics.
       e-mail: ronnyk@sgi.com for questions.

Split into train-test using MLC++ GenCVFiles (2/3, 1/3 random).

48842 instances, mix of continuous and discrete    (train=32561, test=16281)

45222 if instances with unknown values are removed (train=30162, test=15060)

Duplicate or conflicting instances : 6

Class probabilities for adult.all file

Probability for the label '>50K'  : 23.93% / 24.78% (without unknowns)

Probability for the label '<=50K' : 76.07% / 75.22% (without unknowns)

  Extraction was done by Barry Becker from the 1994 Census database.  A set of
  reasonably clean records was extracted using the following conditions:
  ((AAGE>16) && (AGI>100) && (AFNLWGT>1)&& (HRSWK>0))

Prediction task is to determine whether a person makes over 50K
a year.

First cited in:
@inproceedings{kohavi-nbtree,
   author={Ron Kohavi},
   title={Scaling Up the Accuracy of Naive-Bayes Classifiers: a
          Decision-Tree Hybrid},
   booktitle={Proceedings of the Second International Conference on
              Knowledge Discovery and Data Mining},
   year = 1996,
   pages={to appear}}

Conversion of original data as follows:
1. Discretized agrossincome into two ranges with threshold 50,000.
2. Convert U.S. to US to avoid periods.
3. Convert Unknown to "?"
4. Run MLC++ GenCVFiles to generate data,test.

Description of fnlwgt (final weight)

The weights on the CPS files are controlled to independent estimates of the
civilian noninstitutional population of the US.  These are prepared monthly
for us by Population Division here at the Census Bureau.  We use 3 sets of
controls.
 These are:
         1.  A single cell estimate of the population 16+ for each state.
         2.  Controls for Hispanic Origin by age and sex.
         3.  Controls by Race, age and sex.

We use all three sets of controls in our weighting program and "rake" through
them 6 times so that by the end we come back to all the controls we used.

The term estimate refers to population totals derived from CPS by creating
"weighted tallies" of any specified socio-economic characteristics of the
population.

People with similar demographic characteristics should have
similar weights.  There is one important caveat to remember
about this statement.  That is that since the CPS sample is
actually a collection of 51 state samples, each with its own
probability of selection, the statement only applies within
state.


age: continuous.

workclass: Private, Self-emp-not-inc, Self-emp-inc, Federal-gov, Local-gov, State-gov, Without-pay, Never-worked.

fnlwgt: continuous.

education: Bachelors, Some-college, 11th, HS-grad, Prof-school, Assoc-acdm, Assoc-voc, 9th, 7th-8th, 12th, Masters, 1st-4th, 10th, Doctorate, 5th-6th, Preschool.

education-num: continuous.

marital-status: Married-civ-spouse, Divorced, Never-married, Separated, Widowed, Married-spouse-absent, Married-AF-spouse.

occupation: Tech-support, Craft-repair, Other-service, Sales, Exec-managerial, Prof-specialty, Handlers-cleaners, Machine-op-inspct, Adm-clerical, Farming-fishing, Transport-moving, Priv-house-serv, Protective-serv, Armed-Forces.

relationship: Wife, Own-child, Husband, Not-in-family, Other-relative, Unmarried.

race: White, Asian-Pac-Islander, Amer-Indian-Eskimo, Other, Black.

sex: Female, Male.

capital-gain: continuous.

capital-loss: continuous.

hours-per-week: continuous.

native-country: United-States, Cambodia, England, Puerto-Rico, Canada, Germany, Outlying-US(Guam-USVI-etc), India, Japan, Greece, South, China, Cuba, Iran, Honduras, Philippines, Italy, Poland, Jamaica, Vietnam, Mexico, Portugal, Ireland, France, 
Dominican-Republic, Laos, Ecuador, Taiwan, Haiti, Columbia, Hungary, Guatemala, Nicaragua, Scotland, Thailand, Yugoslavia, El-Salvador, Trinadad&Tobago, Peru, Hong, Holand-Netherlands.


In [2]:
# Load in data

columns = [
    'age',
    'workclass',
    'fnlwgt',
    'education',
    'education_num',
    'marital_status',
    'occupation',
    'relationship',
    'race',
    'sex',
    'capital-gain',
    'capital-loss',
    'hours-per-week',
    'native-country',
    'income'
    
]
df = pd.read_csv('../Resources/data.csv', header=None, names=columns, index_col=False)
df

age          workclass  fnlwgt    education  education_num  \
0       39          State-gov   77516    Bachelors             13   
1       50   Self-emp-not-inc   83311    Bachelors             13   
2       38            Private  215646      HS-grad              9   
3       53            Private  234721         11th              7   
4       28            Private  338409    Bachelors             13   
...    ...                ...     ...          ...            ...   
32556   27            Private  257302   Assoc-acdm             12   
32557   40            Private  154374      HS-grad              9   
32558   58            Private  151910      HS-grad              9   
32559   22            Private  201490      HS-grad              9   
32560   52       Self-emp-inc  287927      HS-grad              9   

            marital_status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital-gain  capital-loss  hours-per-week  native-country  \
0         Male          2174             0              40   United-States   
1         Male             0             0              13   United-States   
2         Male             0             0              40   United-States   
3         Male             0             0              40   United-States   
4       Female             0             0              40            Cuba   
...        ...           ...           ...             ...             ...   
32556   Female             0             0              38   United-States   
32557     Male             0             0              40   United-States   
32558   Female             0             0              40   United-States   
32559     Male             0             0              20   United-States   
32560   Female         15024             0              40   United-States   

       income  
0       <=50K  
1       <=50K  
2       <=50K  
3       <=50K  
4       <=50K  
...       ...  
32556   <=50K  
32557    >50K  
32558   <=50K  
32559   <=50K  
32560    >50K  

[32561 rows x 15 columns]

In [3]:
# Drop the label to create the X data
X = df.drop('income', axis=1)
X

age          workclass  fnlwgt    education  education_num  \
0       39          State-gov   77516    Bachelors             13   
1       50   Self-emp-not-inc   83311    Bachelors             13   
2       38            Private  215646      HS-grad              9   
3       53            Private  234721         11th              7   
4       28            Private  338409    Bachelors             13   
...    ...                ...     ...          ...            ...   
32556   27            Private  257302   Assoc-acdm             12   
32557   40            Private  154374      HS-grad              9   
32558   58            Private  151910      HS-grad              9   
32559   22            Private  201490      HS-grad              9   
32560   52       Self-emp-inc  287927      HS-grad              9   

            marital_status          occupation    relationship    race  \
0            Never-married        Adm-clerical   Not-in-family   White   
1       Married-civ-spouse     Exec-managerial         Husband   White   
2                 Divorced   Handlers-cleaners   Not-in-family   White   
3       Married-civ-spouse   Handlers-cleaners         Husband   Black   
4       Married-civ-spouse      Prof-specialty            Wife   Black   
...                    ...                 ...             ...     ...   
32556   Married-civ-spouse        Tech-support            Wife   White   
32557   Married-civ-spouse   Machine-op-inspct         Husband   White   
32558              Widowed        Adm-clerical       Unmarried   White   
32559        Never-married        Adm-clerical       Own-child   White   
32560   Married-civ-spouse     Exec-managerial            Wife   White   

           sex  capital-gain  capital-loss  hours-per-week  native-country  
0         Male          2174             0              40   United-States  
1         Male             0             0              13   United-States  
2         Male             0             0              40   United-States  
3         Male             0             0              40   United-States  
4       Female             0             0              40            Cuba  
...        ...           ...           ...             ...             ...  
32556   Female             0             0              38   United-States  
32557     Male             0             0              40   United-States  
32558   Female             0             0              40   United-States  
32559     Male             0             0              20   United-States  
32560   Female         15024             0              40   United-States  

[32561 rows x 14 columns]

In [4]:
# One-hot encoding the 'workclass' column creates 9 new columns, one for each category
pd.get_dummies(X['workclass'])

?   Federal-gov   Local-gov   Never-worked   Private   Self-emp-inc  \
0       0             0           0              0         0              0   
1       0             0           0              0         0              0   
2       0             0           0              0         1              0   
3       0             0           0              0         1              0   
4       0             0           0              0         1              0   
...    ..           ...         ...            ...       ...            ...   
32556   0             0           0              0         1              0   
32557   0             0           0              0         1              0   
32558   0             0           0              0         1              0   
32559   0             0           0              0         1              0   
32560   0             0           0              0         0              1   

        Self-emp-not-inc   State-gov   Without-pay  
0                      0           1             0  
1                      1           0             0  
2                      0           0             0  
3                      0           0             0  
4                      0           0             0  
...                  ...         ...           ...  
32556                  0           0             0  
32557                  0           0             0  
32558                  0           0             0  
32559                  0           0             0  
32560                  0           0             0  

[32561 rows x 9 columns]

In [5]:
# One-hot encoding the entire dataframe
X_dummies = pd.get_dummies(X)
print(X_dummies.columns)
X_dummies

Index(['age', 'fnlwgt', 'education_num', 'capital-gain', 'capital-loss',
       'hours-per-week', 'workclass_ ?', 'workclass_ Federal-gov',
       'workclass_ Local-gov', 'workclass_ Never-worked',
       ...
       'native-country_ Portugal', 'native-country_ Puerto-Rico',
       'native-country_ Scotland', 'native-country_ South',
       'native-country_ Taiwan', 'native-country_ Thailand',
       'native-country_ Trinadad&Tobago', 'native-country_ United-States',
       'native-country_ Vietnam', 'native-country_ Yugoslavia'],
      dtype='object', length=108)


age  fnlwgt  education_num  capital-gain  capital-loss  hours-per-week  \
0       39   77516             13          2174             0              40   
1       50   83311             13             0             0              13   
2       38  215646              9             0             0              40   
3       53  234721              7             0             0              40   
4       28  338409             13             0             0              40   
...    ...     ...            ...           ...           ...             ...   
32556   27  257302             12             0             0              38   
32557   40  154374              9             0             0              40   
32558   58  151910              9             0             0              40   
32559   22  201490              9             0             0              20   
32560   52  287927              9         15024             0              40   

       workclass_ ?  workclass_ Federal-gov  workclass_ Local-gov  \
0                 0                       0                     0   
1                 0                       0                     0   
2                 0                       0                     0   
3                 0                       0                     0   
4                 0                       0                     0   
...             ...                     ...                   ...   
32556             0                       0                     0   
32557             0                       0                     0   
32558             0                       0                     0   
32559             0                       0                     0   
32560             0                       0                     0   

       workclass_ Never-worked  ...  native-country_ Portugal  \
0                            0  ...                         0   
1                            0  ...                         0   
2                            0  ...                         0   
3                            0  ...                         0   
4                            0  ...                         0   
...                        ...  ...                       ...   
32556                        0  ...                         0   
32557                        0  ...                         0   
32558                        0  ...                         0   
32559                        0  ...                         0   
32560                        0  ...                         0   

       native-country_ Puerto-Rico  native-country_ Scotland  \
0                                0                         0   
1                                0                         0   
2                                0                         0   
3                                0                         0   
4                                0                         0   
...                            ...                       ...   
32556                            0                         0   
32557                            0                         0   
32558                            0                         0   
32559                            0                         0   
32560                            0                         0   

       native-country_ South  native-country_ Taiwan  \
0                          0                       0   
1                          0                       0   
2                          0                       0   
3                          0                       0   
4                          0                       0   
...                      ...                     ...   
32556                      0                       0   
32557                      0                       0   
32558                      0                       0   
32559                      0                       0   
32560                      0           

In [6]:
# Converting output labels to 0 and 1
y_label = LabelEncoder().fit_transform(df['income'])
y_label

array([0, 0, 0, ..., 0, 0, 1])

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X_dummies, y_label, random_state=1)

In [8]:
# Scaling the X data by using StandardScaler()
scaler = StandardScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_train_scaled

array([[ 0.90894294,  0.88870638, -0.42454163, ...,  0.34079138,
        -0.04483956, -0.022173  ],
       [-0.19050856, -0.66000898,  1.12727615, ...,  0.34079138,
        -0.04483956, -0.022173  ],
       [-0.63028916, -0.24294561,  1.90318504, ...,  0.34079138,
        -0.04483956, -0.022173  ],
       ...,
       [-0.85017946, -0.80615511,  1.12727615, ..., -2.93434654,
        -0.04483956, -0.022173  ],
       [ 1.49531708,  0.74245653, -0.42454163, ...,  0.34079138,
        -0.04483956, -0.022173  ],
       [-0.41039886, -1.23397672,  1.12727615, ...,  0.34079138,
        -0.04483956, -0.022173  ]])

In [9]:
# Alternatively, scaling the data by using MinMaxScaler()
scaler = MinMaxScaler().fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_train_scaled

array([[0.46575342, 0.18385708, 0.53333333, ..., 1.        , 0.        ,
        0.        ],
       [0.26027397, 0.07219077, 0.8       , ..., 1.        , 0.        ,
        0.        ],
       [0.17808219, 0.1022621 , 0.93333333, ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.1369863 , 0.06165326, 0.8       , ..., 0.        , 0.        ,
        0.        ],
       [0.57534247, 0.1733121 , 0.53333333, ..., 1.        , 0.        ,
        0.        ],
       [0.21917808, 0.03080623, 0.8       , ..., 1.        , 0.        ,
        0.        ]])

In [10]:
# Transforming the test dataset based on the fit from the training dataset
X_test_scaled = scaler.transform(X_test)
X_test_scaled

array([[0.61643836, 0.00893445, 0.2       , ..., 1.        , 0.        ,
        0.        ],
       [0.01369863, 0.13211588, 0.4       , ..., 1.        , 0.        ,
        0.        ],
       [0.10958904, 0.0603065 , 0.8       , ..., 1.        , 0.        ,
        0.        ],
       ...,
       [0.15068493, 0.06354253, 0.46666667, ..., 1.        , 0.        ,
        0.        ],
       [0.38356164, 0.11741095, 0.53333333, ..., 1.        , 0.        ,
        0.        ],
       [0.02739726, 0.207387  , 0.6       , ..., 1.        , 0.        ,
        0.        ]])